### ISSUE TITLE
A suggestion to solve the "information blinking" issue (recorded in a video)

### ISSUE THREAD

**Issue by DRSAgile** [FelixdelasPozas/TrayWeather#125] opened 2022-07-25 06:58 UTC
Hi, Felix,

This is not a new issue, but this time I got it recorded in a short video:
https://disk.yandex.ru/i/_BrQWOKIHJuRYg

Occasionally, presumably due to weather service server glitching, it makes the application show "Error requesting weather data" red cloud icons instead.

However, that message is **false** since if I click on "Refresh" in the context menu, the tray is showing the weather just fine, but immediately after that reverts back to the error message. I checked: the weather data that is blinking is real and accurate, it is not something random.

In the code of the application, something forces it to go to the error state even if the weather data was already actually received successfully and even displayed like a half second ago just fine.

My suggestion is to look at the code to stop it from doing this. After showing the weather, it should not want to immediately receive some more data, but even if it does, it should not break the good data it received just fine, it should not tamper with the icons.

Additionally, as also seen in the linked video, if I am not clicking on "Refresh", but rather double-click on the tray icons instead, I get a window with full weather details opened. And, this time, the weather data in the icons does not immediately go anywhere, meaning that **in this case** the code does not go to the area that forces it into an error, unlike when I click on "Refresh".

Both phenomenons are repeated behaviours.

(I have no proxy, and I have the most basic simple configuration setting, as seen in the video; though no other setting configuration fixes this.)
 
Thanks in advance.

**Comment by adem4ik** [comment] 2022-07-26 02:58
Version: 1.23.0
I have the same issue since yesterday: https://recordit.co/GPM2ztUNyV

**Comment by FelixdelasPozas** [comment] 2022-07-26 06:19
Hi @DRSAgile  and @adem4ik .

I'm also having the same issue since yesterday. Weather forecast data is received without problems (that's why the first call succeeds and shows the icon/temp correctly), but the pollution data server is not and that is the error that the application is showing. 

![Clipboard](https://user-images.githubusercontent.com/12167134/180936200-050d6071-7118-441c-be3c-4f0063c63f1c.png)

The "blinking" now is due to it being two separated network calls and the second one fails. I gotta do something about the widgets/charts "with no data" and the error icon. 
This last weeks of this month have been rather slow because there are a lot of things to finish before everyone goes on vacation, but I'll try to fix this and the other planned thing (maps scales colors) soon.

Regards, 
Félix.

**Comment by RopoTrop** [comment] 2022-07-28 07:22
Thanks for confirming the problem, just wanted to say I have it also. Now on 1.23, but 1.06 was having the same behaviour... Cheers, thanks for the app.

**Comment by FelixdelasPozas** [comment] 2022-08-12 18:25
Hello @DRSAgile , @adem4ik and @RopoTrop .

In the next version the tray icon will only change to the error icon when the geolocation (if activated) or current weather data cannot be obtained. If any of the forecasts is incomplete or there is a network error when obtaining the data, it will be shown in the related application tab itself. Like this: 
![Clipboard01](https://user-images.githubusercontent.com/12167134/184420463-072bbb16-e157-4a32-9515-d184ae604824.png)
Also a little error message will be introduced in the tooltip if there is space for it (the tooltip text for a tray icon is limited to 127 characters). I had little time to test it, but seems it'll work as intended. 

Hope this solves the "blinking" problem. The next version will be released once I have all the translations for the new texts. 

Regards, 
Félix.

**Comment by DRSAgile** [comment] 2022-08-12 18:48
Thanks, Félix.

Maybe something for the future, if possible: an alternative data provider. This one is quite glitchy too often, and I do not mean the "blinking" issue, but in general. It regularly forces me to switch between settings, though it does not really help if it is in bad mood, so to speak.

The application might ping a secondary weather data source is the primary is not responding -- and doing it silently, with no errors or red clouds icons.

And this secondary weather data source does not have to be a formal API like the primary. Depending on the site, just a regular HTML page with weather data can be downloaded with the use of a URL containing a city/country and then be parsed (with `RegExp` or `XPath` or whatever is more convenient) to get at least the current temperature and the cloud situation. In such a case, no key validation, electronic mail registration or anything would be necessary.

For example, the following link returns a page with weather for NY, based on its coordinates (latitude and longitude):
[https://yandex.ru/pogoda/?lat=40.7128&lon=-74.0060](https://yandex.ru/pogoda/?lat=40.7128&lon=-74.0060)

Thanks in advance.

**Comment by FelixdelasPozas** [comment] 2022-08-12 20:20
Hi @DRSAgile .

In fact there is a bunch of [free weather API](https://github.com/public-apis/public-apis#weather) available.  The important differences are always: 
- Part of the world covered (hopefully all).
- Weather forecasts for at least 5 days. 
- Maps (better if interactive).

The last time I checked the [Meteorologisk Institutt](https://api.met.no/weatherapi/documentation) covered most of the requirements and did not require to register, but weak in the "Maps" category. I've not entered into the "weather data quality" or, in the case you mention, availability. OpenweatherMap free claims to have 95% uptime. Usually the others do not report that or claim more or less the same 95-99% uptime (usually in their commercial service).

I don't have much free time lately, but I promise I'll look into it again soon. And maybe refactor the code of the application to make the provider "abstract" so the implementation of different data providers is easy and fast. 

Maybe I should open a thread in "Discussions" to leave open there instead here in an "issue".

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment] 2022-08-22 20:17
The [1.24 release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.24.0) should alleviate the problem. Only connection problems that the application couldn't recover (as not being able to geo-locate or get current weather data) will appear in the tray icon. The rest of the errors (the more common ones, like the one that have been occurring with pollution data) will appear in the related tab in the forecast dialog. 

For the next release I'll start refactoring the data provider code to make it easy to add different data providers. 

Regards, 
Félix.

**Closed by FelixdelasPozas** 2022-08-22 20:17 UTC
Labels: bug, visuals
