### ISSUE TITLE
Unable to select a language on first use.

### ISSUE THREAD

**Issue by cmhrky** [FelixdelasPozas/TrayWeather#134] opened 2022-10-16 12:06 UTC
Hi,

Unable to select a language when the application is opened after installing it for the first time. It closes with the following warning.

![image](https://user-images.githubusercontent.com/17867666/196034416-aaf20a84-c004-4b43-9c58-080a714a5095.png)

Can the application make automatic language selection according to the language of the system?
Or is it possible to select a language on the first run?

**Comment by FelixdelasPozas** [comment] 2022-10-16 15:01
Hi @cmhrky . 

That message appears only when the **OpenWeatherMap API Key** field is empty or incorrect in the first tab of the configuration. Check that your Key is entered correctly or, if you just asked for one (in the OpenWeatherMap website, a key is necessary), you might have to wait an hour or so until the key is valid.

Regards, 
Félix.

**Comment by cmhrky** [comment] 2022-10-16 15:06
I want to make these settings in the language of my choice.

**Comment by FelixdelasPozas** [comment] 2022-10-16 15:10
On the first use (without any configuration) the application should open the Configuration dialog, and in that dialog the last tab contains the language field. Changing it will translate the UI instantly and you'll be able to configure it in your language. 
When starting the application checks for a valid configuration, if there is none it will open the Configuration dialog, every time. If something different is happening it might be a bug. Can you upload a small video so I can see what is happening?

**Comment by cmhrky** [comment] 2022-10-16 15:34
https://user-images.githubusercontent.com/17867666/196044160-8c17ed50-93ee-4ae9-8124-c149539ecbb8.mp4

**Comment by cmhrky** [comment] 2022-10-16 15:48
![Video_2022-10-16_183004](https://user-images.githubusercontent.com/17867666/196044860-396db0cf-2436-449b-8bfb-17808854f03d.gif)

**Comment by FelixdelasPozas** [comment] 2022-10-16 15:58
It seems to be a bug, the language should change as soon as the user selects it. I'll release a fix as soon as possible. Thanks!

**Comment by FelixdelasPozas** [comment] 2022-10-16 22:57
Try the latest [release 1.26.1](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.26.1) it should fix the problem and work as intended, changing the language once the user selects a new one.
This should solve it, but I'll wait for your confirmation to close the issue.

**Comment by cmhrky** [comment] 2022-10-17 09:43
Thanks for the new version. I didn't see any problem. Working properly.

**Comment by FelixdelasPozas** [comment] 2022-10-17 09:52
Great! Closing the issue as fixed.

**Closed by FelixdelasPozas** 2022-10-17 09:52 UTC
